// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAcAaDyzxkvKmuKhgATV3iWhCKZPkSQ6U',
    appId: '1:218889734953:web:156be0d364433aaeb70538',
    messagingSenderId: '218889734953',
    projectId: 'trim-convict',
    authDomain: 'trim-convict.firebaseapp.com',
    storageBucket: 'trim-convict.appspot.com',
    measurementId: 'G-8G8TDVZ73X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RdtQCzDvULdQOBv90cPfl-jZ4xifaTM',
    appId: '1:218889734953:android:c0f272f3099bc214b70538',
    messagingSenderId: '218889734953',
    projectId: 'trim-convict',
    storageBucket: 'trim-convict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyiewsdSeTtWNJAq5Ld94IxLcSM7EWtg',
    appId: '1:218889734953:ios:53141704887b7fccb70538',
    messagingSenderId: '218889734953',
    projectId: 'trim-convict',
    storageBucket: 'trim-convict.appspot.com',
    iosClientId: '218889734953-gmnml6led8rbkuus7vpm4pijkgg06i9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trimConvict',
  );
}
